title: bwnl.io
email: wm@mengw.io
description: BWNL Packages Index
url: https://bwnl.io
github_username: WMXPY
theme: minima
repository: WMXPY/bwnl.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
